config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#home'
  get '/about' => 'homes#about'

  resources :users, only:[:show, :index, :edit, :update] do
     get '/follower' => 'relationships#follower'
     get '/followed' => 'relationships#followed'
    resource :relationships, only: [:create, :destroy]

    get '/list' => 'book_comments#list'
end

  resources :books, only:[:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments do
      resources :comment_favorites, only:[:create, :destroy]
    end
  end
  get 'search' => 'searches#seach'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    def favorite_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

    belongs_to :user
    belongs_to :book
    has_many :comment_favorite, dependent: :destroy

     def bfavorite_by?(user)
        comment_favorites.where(user_id: book_comment.id).exists?
     end
end

app/models/comment_favorite.rb
class CommentFavorite < ApplicationRecord

  belongs_to :user
  belongs_to :book_comment
  belongs_to :comment_favorite

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :book
    belongs_to :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   attachment :profile_image
   has_many :books, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :comment_favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy

   has_many :relationships, class_name: "Relationship", foreign_key: :follower_id
   #has_many :followeds, through: :relationships, source: :follower
   has_many :followings, through: :relationships, source: :followed
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id
  # has_many :followers, through: :reverse_of_relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower

     def follow(user_id)
       relationships.create(followed_id: user_id)
     end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search(keyword)
    if search
      User.where(['name LIKE ?', "%#{keyword}%"])
    else
      User.all
    end
  end


   validates :name, presence: true, length: { in: 2..20 }
   validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
     before_action :configure_permitted_parameters, if: :devise_controller?
     before_action :authenticate_user!, except: [:about, :home]

     def after_sign_in_path_for(resource)
       user_path(resource)
     end
     
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    
    def create
        book = Book.find(params[:book_id])
        comment = BookComment.new(book_comment_params)
        comment.user_id = current_user.id
        comment.book_id = book.id
        comment.save
        redirect_to request.referer
    end
    
    def destroy
        #book = Book.find(params[:book_id])
        comment = BookComment.find(params[:id])
        comment.destroy
        redirect_to request.referer
    end
    
    def list
        @user = User.find(params[:user_id])
        @comments = @user.book_comments#eachでコメント取り出せる
        @favorites = @user.favorites
        
    end
    
    private
    
    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
        @book = Book.new
        @user = current_user

    end

    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
          flash[:notice] = "successfully"
         redirect_to user_path(@book.user_id)
      else
          @books = Book.all
          @user = current_user
          render :index
      end
    end

    def show
        @comment = BookComment.find(params[:id])
        @book = Book.find(params[:id])
        @user = @book.user
        @book_show = Book.new
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        redirect_to books_path unless current_user == @book.user_id
    end

    def update
        @book = Book.find(params[:id])
        @book.user_id = current_user.id
        if @book.update(book_params)
           flash[:notice] = "successfully"
           redirect_to book_path(@book.id)
        else
           render :edit
        end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    private

    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
        book = Book.find(params[:book_id])
        favorite = Favorite.new(user_id: current_user.id, book_id: book.id)
        #favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        #redirect_back(fallback_location: root_path)
        redirect_to request.referer

    end
    
    def destroy
        book = Book.find(params[:book_id])
        favorite = Favorite.find_by(user_id: current_user.id, book_id: book.id)
        #favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
       # redirect_back(fallback_location: root_path)
        redirect_to request.referer

    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
  def home
  end
    
  def about
  end
    
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @user = User.search(params[:keyword])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @users = User.all
  @user = current_user
  @book = Book.all
end

def show
  @user = User.find(params[:id])
  @book = Book.new
  @books = @user.books
end

def edit
  @user = User.find(params[:id])
  redirect_to user_path(current_user.id) unless current_user.id == @user.id
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
     flash[:notice] = "successfully" 
     redirect_to user_path(@user.id)
  else
     render :edit
  end
end

private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comment_favorites_helper.rb
module CommentFavoritesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= attachment_image_tag current_user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg", size:"40x40" %>としてコメント
<%= form_with model:[book, book_comment], method: :post, local:true, class: "form-inline" do |f| %> <!--url: book_book_comments-->
  <div class="form-group">
   <%= f.label :comment, class: "sr-only" %><br>
   <%= f.text_area :comment, class: "form-control" %>
  </div>
  <dev class="form-group">
   <%= f.submit "create" %>
  </dev>

<% end %>

app/views/book_comments/list.html.erb
 <div class="table">
<h2>いいねした投稿</h2>
<table>
    <thead>
        <th>タイトル</th>
        
    </thead>
    <tbody>
        <% @favorites.each do |favorite| %>
        <tr>
        <td>
            <li><%= link_to book_path(favorite.book) do %>
                <%= favorite.book.title %>
                 <% end %>
         </li>
         </td>
         </tr>
        <% end %>
    </tbody>
</table>
</div>


 <div class="table">
<h2>コメントした投稿</h2>
<table>
    <thead>
        <th>タイトル</th>
        <th>コメント内容</th>
    </thead>
    <tbody>
        <% @comments.each do |comment| %>
        <tr>
        <td><%= link_to book_path(comment.book) do %>
         <%= comment.book.title %>
         <% end %></td>
         <td><%= comment.comment %></td>
         </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/books/_form.html.erb
 
  <%= form_with model:book,url: books_path, method: :post, local:true do |f| %> <!-- url: books_path, method: :post, -->
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control book_title" %>
</div>   
<div class="form-group"> 
  <%= f.label :opinion %>
  <%= f.text_area :body, class: "form-control book_title" %>
</div>   
<div class="form-group"> 
  <%= f.submit "create" %>
</div>  
<% end %>

app/views/books/edit.html.erb
<h2>Book edit</h2>

  <ul><% if @book.errors.any? %>
 <h3><%= @book.errors.count %>件のerrorです</h3>
 <%= @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 <% end %></ul>
 
<%= form_with model:@book, local: true do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>
  
  <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
  </div>
  
  <div>
      <%= f.submit "update" %>
  </div>
 <% end %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  
      
  <ul><% if @book.errors.any? %>
 <h3><%= @book.errors.count %>件のerror</h3>
 <%= @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 <% end %></ul>
 
 <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
    <%= render 'users/info', user: @user %>
    <h2 class="mt-3">New Book</h2>
    <%= render 'books/form', book: @book%>
  </div>
  
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
        <thead>
            <tr>
                <td></td>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <tbody>
            
              <% @books.each do |book| %>
              <tr>
              <td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"40x40" %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
                <% if book.favorite_by?(current_user) %>
                   <td><%= link_to book_favorites_path(book.id), method: :delete do %>
                     <i class="fas fa-thumbs-up"></i><%= book.favorites.count %>
                   <% end %></td>
                <% else %>
                    <td><%= link_to book_favorites_path(book.id), method: :post do %>
                      <i class="far fa-thumbs-up"></i><%= book.favorites.count %>
                    <% end %></td>
                <% end %>
                <td>コメント数：<%= book.book_comments.count %></td>
              </tr>
              <% end %>
            
      </tbody>
    </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <% if flash[:notice] %>
    <p id="notice">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New Book</h2>
      <%= render 'books/form', book: @book_show%>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <%= render 'book_comments/form', book_comment: @book_comment, book: @book %>
      <table class="table table-hover table-inverse">
        <thead>
          <td>
          <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg", size:"40x40" %><br>
            <%= @user.name %>
          <% end %></td>
          <td><%=  @book.title %></td>
          <td><%=  @book.body %></td>

　     　 <% if @book.favorite_by?(current_user) %>
            <td>
            <%= link_to book_favorites_path(@book.id), method: :delete do %>
              <i class="fas fa-thumbs-up"><%= @book.favorites.count %>
            <% end %></td>
          <% else %>
            <td>
            <%= link_to book_favorites_path(@book.id), method: :post do %>
              <i class="far fa-thumbs-up"><%= @book.favorites.count %><br>
            <% end %></td>
          <% end %>
          <td><span class="date"><%= time_ago_in_words(@book.created_at) %> ago</span></td>

          <% if current_user.id == @user.id %>
            <td><%= link_to "Edit",  edit_book_path(@book.id) %></td>
            <td><%= link_to "Delete",  book_path(@book.id), method: :delete %></td>
          <% end %>
        </thead>
        <tbody>
          <tr>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
            <% @book.book_comments.each do |comment| %>
              <td>
              <%= link_to user_path(comment.user.id) do %>
                <%= attachment_image_tag comment.user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg", size:"40x40" %><br>
                <%= comment.user.name %>
              <% end %></td>
              <td><%= comment.comment %></td>

              　 <% if @comment.bfavorite_by?(current_user) %>
          <% else %>
            <td>
            <%= link_to book_favorites_path(@book.id, @comment.id), method: :post do %>
              <i class="far fa-thumbs-up"><%= @comment.favorites.count %><br>
            <% end %></td>
          <% end %>

              <td><span class="date"><%= time_ago_in_words(comment.created_at) %> ago</span></td>
              <% if comment.user.id == current_user.id %>
                <td><%= link_to "Delete", book_book_comment_path(@book.id, comment.id), method: :delete %></td>
              <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_info.html.erb
<%= attachment_image_tag user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg", size:"62x62" %>
<%= link_to "詳細", user_list_path(user) %>
<table class = "table">
  <tbody>
    <tr>
       <th>name</th>
       <th><%= user.name%></th>
    </tr>
    <tr>
       <th>Introduction</th>
       <th><%= user.introduction %></th>
    </tr>
    <tr>
      <td>フォロワー数：</td>
      <td>
        <%= link_to user_follower_path(user) do %>
        <%= user.followers.count %>
        <% end %>
        </td>
    </tr>
    <tr>
      <td>フォロー数：</td>
      <td>
        <%= link_to user_followed_path(user) do %>
        <%= user.followings.count %>
        <% end %>
        </td>
    </tr>
    <% if user != current_user %>
    <tr>
       <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    </tr>
    <% end %>
       <td><%= link_to edit_user_path(user.id) do %>
          <%= image_tag('setting.jpg', size: '40x30') %>
        <% end %>
       </td>

  </tbody>
  </table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User edit</h2>
      <ul>
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>件のerror</h3>
          <%= @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </ul>
      <%= form_with model:@user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %><br/>
            <%= f.text_field :name, autofocus: true %>
        </div>
        <div class="form-group">
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %><br>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.submit "update", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
    <%= render 'users/info', user: @user %>
    <h2 class="mt-3">New Book</h2>
    <%= render 'books/form', book: @book%>
  </div>

    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <th>image</th>
        <th>name</th>
        <th>introduction</th>
        <th></th>
        <th></th>
      </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user_path(user.id) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"40x40" %>
        <% end %></td>
        <td><%= user.name %></td>
        <td><%= user.introduction %></td>
        <% if current_user == user %>
          <td></td>
          <td></td>
          <td></td>
        <% else %>
          <% if current_user.following?(user) %>
            <td><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
          <% end %>
      <td><%= link_to "show", user_path(user.id) %></td>
        <% end %>
     <% end %>
     </tr>
     </tbody>
     </table>
     </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  
    <% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
  <% end %>
  
  <div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
    <%= render 'users/info', user: @user %>
    <h2 class="mt-3">New Book</h2>
    <%= render 'books/form', book: @book%>
  </div>


  <div class="col-md-8 offset-md-1">
    <h2>books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <% @books.each do |book| %>
          <tr>
          <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"40x40" %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>