config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#home'
  get '/about' => 'homes#about'

  resources :users, only:[:show, :index, :edit, :update] do
     get '/follower' => 'relationships#follower'
     get '/followed' => 'relationships#followed'
    resource :relationships, only: [:create, :destroy]

    get '/list' => 'book_comments#list'
end

  resources :books, only:[:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments do
      resources :comment_favorites, only:[:create, :destroy]
    end
  end
  get 'search' => 'searches#seach'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    def favorite_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

    belongs_to :user
    belongs_to :book
    has_many :comment_favorite, dependent: :destroy

     def bfavorite_by?(user)
        comment_favorites.where(user_id: book_comment.id).exists?
     end
end

app/models/comment_favorite.rb
class CommentFavorite < ApplicationRecord

  belongs_to :user
  belongs_to :book_comment
  belongs_to :comment_favorite

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :book
    belongs_to :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   attachment :profile_image
   has_many :books, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :comment_favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy

   has_many :relationships, class_name: "Relationship", foreign_key: :follower_id
   #has_many :followeds, through: :relationships, source: :follower
   has_many :followings, through: :relationships, source: :followed
   has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id
  # has_many :followers, through: :reverse_of_relationships, source: :followed
   has_many :followers, through: :reverse_of_relationships, source: :follower

     def follow(user_id)
       relationships.create(followed_id: user_id)
     end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search(keyword)
    if search
      User.where(['name LIKE ?', "%#{keyword}%"])
    else
      User.all
    end
  end


   validates :name, presence: true, length: { in: 2..20 }
   validates :introduction, length: { maximum: 50 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
        @book = Book.new
        @user = current_user

    end

    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
          flash[:notice] = "successfully"
         redirect_to user_path(@book.user_id)
      else
          @books = Book.all
          @user = current_user
          render :index
      end
    end

    def show
        @comment = BookComment.find(params[:id])
        @book = Book.find(params[:id])
        @user = @book.user
        @book_show = Book.new
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        redirect_to books_path unless current_user == @book.user_id
    end

    def update
        @book = Book.find(params[:id])
        @book.user_id = current_user.id
        if @book.update(book_params)
           flash[:notice] = "successfully"
           redirect_to book_path(@book.id)
        else
           render :edit
        end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    private

    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
        book = Book.find(params[:book_id])
        favorite = Favorite.new(user_id: current_user.id, book_id: book.id)
        #favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        #redirect_back(fallback_location: root_path)
        redirect_to request.referer

    end
    
    def destroy
        book = Book.find(params[:book_id])
        favorite = Favorite.find_by(user_id: current_user.id, book_id: book.id)
        #favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
       # redirect_back(fallback_location: root_path)
        redirect_to request.referer

    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
  def home
  end
    
  def about
  end
    
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @user = User.search(params[:keyword])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @users = User.all
  @user = current_user
  @book = Book.all
end

def show
  @user = User.find(params[:id])
  @book = Book.new
  @books = @user.books
end

def edit
  @user = User.find(params[:id])
  redirect_to user_path(current_user.id) unless current_user.id == @user.id
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
     flash[:notice] = "successfully" 
     redirect_to user_path(@user.id)
  else
     render :edit
  end
end

private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>B<%= image_tag('boll.jpg', size: '10x10') %><%= image_tag('boll.jpg', size: '10x10') %>kers</span>
      </a>
      <button class="navbar-toggler" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>
            <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
            <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
            <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
          <% else %>
            <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
            <%= link_to "About", about_path, class: "fas fa-link nav-link text-light" %>
            <%= link_to "Sing in", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
            <%= link_to "Log in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
         <% end %>

        </ul>
      </div>
    </div>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/header' %>
  <%= render 'searches/search' %>
  <body>
    <%= yield %>
  </body>
</html>